### ISSUE TITLE
Change setHeader param to be non null

### ISSUE THREAD

**Issue by digitalbuddha** [Genius/groupie#4]
Null's make my head hurt.  How do you feel about making `setHeader` @nonNull and adding `removeHeader`.

**Comment by lisawray** [comment]
On reflection, I feel good about it. :)

**Comment by digitalbuddha** [comment]
I'll open a pr tonight

**Comment by digitalbuddha** [comment]
Is there a style guide I can follow?

**Comment by lisawray** [comment]
Basically, standard Android style without prefix/Hungarian notation.  I
haven't been too strict about it.  I just hate `mVariables`. :)

**Comment by digitalbuddha** [comment]
It seems bit odd. Like annotation on same line as instance type
declaration.

I think a few other things were a bit off spacing wise. Anyways just making
sure I don't break anything. :-)

**Comment by lisawray** [comment]
I don't have it failing on style checks or anything.  We're not that sophisticated around here yet.  I'm pretty sure you'll have to update the unit tests, though!

**Comment by digitalbuddha** [comment]
Tests were fixed, a couple of new tests were added as well.  Let me know if you need anything else

**Comment by lisawray** [comment]
It looks good and I see the tests passed!  I'll look at it tonight :)

**Comment by lisawray** [comment]
#17
