### ISSUE TITLE
ExpandableGroup items have no animation while expanding or collapsing and feel not smooth 

### ISSUE THREAD

**Issue by shakil807g** [Genius/groupie#50]
Expandable group is not smooth as how Epoxy handle expand and collapse which is so much smooth as compare to groupie  is there is way  achieved custom expand or collapse animation  and how can i achieved the underline data model in Adapter like Epoxy which i found very flexible

**Comment by lisawray** [comment]
Hi @shakil807g , thanks for trying groupie :)  I'm also a big fan of Epoxy.  

As far as your question about expanding and collapsing, can you send me a sample project or video (preferably both) showing the implementation you prefer with Epoxy?  As far as I know, neither project includes their own custom item animators so the default animation should be very similar.

As for underlying data models, the closest analog to an `EpoxyModel` in Groupie is an `Item`. You can store whatever pure model object you like inside it.

**Comment by lisawray** [comment]
I'm closing this question, but please feel free to re-open it if you have additional data about a bug in animation!
