### ISSUE TITLE
Methods to cleanup an Item

### ISSUE THREAD

**Issue by andhie** [Genius/groupie#51]
The way the Item object is designed, it only has bind() methods. It does not seem there are methods expose for cleaning up the ViewHolder/Binding. 

Example, if you have a chat recyclerview, you have a VideoViewItemBinding. User can click to play the VideoView, when user scroll it away, we do not receive any callback to stop() or release any resources.

**Comment by kjpublic01** [comment]
#15 is a placeholder for this enhancement.

**Comment by lisawray** [comment]
yep -- thanks @kjpublic01!  thanks for pointing this out @andhie .  I'm hoping to get a few minutes over the New Year to add some new functionality.  I'm also always happy to merge PRs. :)
