### ISSUE TITLE
Section.remove notifies incorrect position

### ISSUE THREAD

**Issue by chip2n** [Genius/groupie#57]
The call to `notifyItemRangeRemoved` inside `Section.remove` uses position calculated from `getPosition`. If I understand the code correctly, it should instead use `getItemCountBeforeGroup` in order to take into account the nested items inside the groups. Was this perhaps missed in 45987d72cb8e2b0d0fad04d6ba8c8e61d493dddd? If so, I'd be happy to send you a pull request.

**Comment by lisawray** [comment]
Quite possible.  The best thing would be a pull request, after that a failing test, otherwise an example!  We started with a bit spotty test coverage so it could easily have slipped through the cracks.

**Comment by lisawray** [comment]
https://github.com/Genius/groupie/pull/67
